export const CATEGORY_KEYWORDS = {
  Produce: [
    "lettuce",
    "tomato",
    "onion",
    "potato",
    "carrot",
    "pepper",
    "apple",
    "orange",
    "berry",
    "berries",
    "banana",
    "avocado",
    "lime",
    "lemon",
    "garlic",
    "ginger",
    "cilantro",
    "basil",
    "parsley",
    "spinach",
    "kale",
    "broccoli",
    "celery",
    "cucumber",
    "zucchini",
    "mushroom",
    "scallion",
    "corn",
    "pear",
    "grape",
    "melon",
    "mango",
    "peach",
    "herbs",
    "salad",
    "arugula",
    "cabbage",
    "squash",
    "sweet potato",
  ],
  "Meat & Seafood": [
    "chicken",
    "beef",
    "pork",
    "steak",
    "salmon",
    "shrimp",
    "fish",
    "turkey",
    "lamb",
    "sausage",
    "bacon",
    "ground",
    "ribs",
    "tilapia",
    "cod",
    "tuna",
    "crab",
    "lobster",
    "meatball",
  ],
  "Dairy & Refrigerated": [
    "milk",
    "cheese",
    "yogurt",
    "cream",
    "butter",
    "egg",
    "eggs",
    "sour cream",
    "cottage",
    "ricotta",
    "mozzarella",
    "parmesan",
    "tortilla",
    "hummus",
    "dip",
    "juice",
    "creamer",
  ],
  "Bread & Bakery": [
    "bread",
    "rolls",
    "buns",
    "bagel",
    "muffin",
    "croissant",
    "pita",
    "tortilla chips",
    "baguette",
    "cake",
    "pie",
    "cookie",
    "pastry",
  ],
  "Dry Goods & Pasta": [
    "pasta",
    "spaghetti",
    "rice",
    "oats",
    "flour",
    "sugar",
    "cereal",
    "granola",
    "quinoa",
    "couscous",
    "lentil",
    "bean",
    "noodle",
    "panko",
    "breadcrumb",
    "cracker",
    "chip",
    "pretzel",
    "nut",
    "almond",
    "peanut",
  ],
  "Canned & Jarred": [
    "canned",
    "can of",
    "jar of",
    "tomato sauce",
    "salsa",
    "pickle",
    "olive",
    "coconut milk",
    "broth",
    "stock",
    "soup",
    "jam",
    "jelly",
    "peanut butter",
    "almond butter",
    "marinara",
    "paste",
  ],
  "Oils, Sauces & Condiments": [
    "oil",
    "vinegar",
    "soy sauce",
    "hot sauce",
    "ketchup",
    "mustard",
    "mayo",
    "mayonnaise",
    "dressing",
    "sriracha",
    "gochujang",
    "sesame oil",
    "fish sauce",
    "worcestershire",
    "honey",
    "maple syrup",
    "teriyaki",
  ],
  Frozen: [
    "frozen",
    "ice cream",
    "pizza rolls",
    "tater tots",
    "popsicle",
    "freezer",
    "waffles",
  ],
  Beverages: [
    "water",
    "soda",
    "sparkling",
    "coffee",
    "tea",
    "beer",
    "wine",
    "liquor",
    "whiskey",
    "vodka",
    "tequila",
    "rum",
    "gin",
    "seltzer",
    "kombucha",
    "la croix",
    "lacroix",
  ],
  "Baby & Kids": [
    "diaper",
    "wipes",
    "formula",
    "baby food",
    "sippy",
    "pacifier",
    "baby",
    "toddler pouch",
  ],
  "Household & Paper": [
    "paper towel",
    "toilet paper",
    "napkin",
    "trash bag",
    "dish soap",
    "detergent",
    "sponge",
    "foil",
    "plastic wrap",
    "ziplock",
    "bag",
    "cleaner",
    "bleach",
    "dryer sheet",
    "laundry",
  ],
};

export const CATEGORY_ORDER = [
  "Produce",
  "Meat & Seafood",
  "Dairy & Refrigerated",
  "Bread & Bakery",
  "Dry Goods & Pasta",
  "Canned & Jarred",
  "Oils, Sauces & Condiments",
  "Frozen",
  "Beverages",
  "Baby & Kids",
  "Household & Paper",
  "Other",
];

export function detectCategory(itemName) {
  const lower = itemName.toLowerCase();
  for (const [cat, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    if (keywords.some((kw) => lower.includes(kw))) return cat;
  }
  return "Other";
}
